### ISSUE TITLE
vector<string>으로 된 커맨드 리스트의 필요성

### ISSUE THREAD

**Issue by armadimon** [armadimon/ft_irc#13]
클라이언트로 받은 문자열을 split한 후에 그대로 함수 포인터를 이용해서 커맨드를 처리하는데, 사전에 정의되지 않은 커맨드가
 map의 key 값에 들어오면 (당연히)segfault가 납니다. 사전에 정의된 커맨드의 리스트가 포함된 std::string을 만들어서 해결하려고 하는데,
다른 좋은 방법 생각나면 무엇이든 댓글로 달아주세요.

**Comment by objectio** [comment]
그러게요 올바른 커맨드 string으로 비교를 하면서 유효성 검사를 하는 게 가장 좋을 것 같네요.

아까 클에서 try ~ catch문으로 예외 처리를 할 수 있지 않을까하는 가설이 떠올랐었는데 std::exception은 오직 c++ error만 handle할 수 있고 low-level 에러는 무시한다고 합니다. 나중에 제가 헷갈릴 수도 있어서 같이 적어놓아요

**Comment by armadimon** [comment]
이 이슈는 간단하게 find로 해결했습니다. 제가 너무 멀리 돌아가는 식으로 생각했었네요
