### ISSUE TITLE
소켓 통신 중 통신이 갑작스럽게 셧다운되는 오류

### ISSUE THREAD

**Issue by objectio** [armadimon/ft_irc#2]
- [x] 클라이언트에서 보낸 메세지 마지막에 이상한 문자가 섞여들어오는 문제
- [x] 통신이 갑작스럽게 닫히는 문제

**Comment by objectio** [comment]
bufRead의 사이즈를 BUF_SIZE + 1로 주었더니 정상적으로 메세지 주고받을 수 있게 됨.

**Comment by armadimon** [comment]
메인 루프에서 로직문제가 있었습니다. fd_max 까지 탐색하는 while loop 블록 안에서 FD_ISSET이 server_socket의 변화를 확인하면 acceptClient를 시도하게끔 바꾸고 select 후에 변화하는 read_fds의 값을 보존하기 위해서 cpy_read_fds를 사용하면서 문제 해결했습니다.

**Comment by armadimon** [comment]
중간에 접속이 종료되는 문제는 계속 발생하는 중. 클라이언트 소켓에서 non_block 특성 설정이 안되있는게 문제라고 판단되서
	fcntl(fd, F_SETFL, O_NONBLOCK);
을 클라이언트 컨스트럭터에 추가해줬음. (테스트중)

테스트 결과 달라지는건 없었음 ㅠㅠ...
클라이언트에서 접속을 끊는건지 서버쪽에서 뭔가 문제가 있는건지 모르겠음.
ping과 pong 커맨드에 대해서도 알아볼 필요성 있음

**Comment by armadimon** [comment]
*******
RFC 2812에 나와있는 RPL_REPLY 001을 보내줘야 Limechat에서는 server에 logged in 했다는 것을 인지하고 몇가지 client to server cmd들을 정상적으로 수행한다 ex) QUIT, NOTICE
연결이 일정시간마다 끊기는 문제도 server의 001 reply를 대기하다가 timeout으로 커넥션을 끊는 것으로 보인다.
001 reply를 추가하여 해결완료!
